mistral-7b-sft-tulu-ufbgpt4_lr-1e-6_epoch-2-10:
  prompt_template: "mistral-7b_sft/prompt_template.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "/fsx-Training/home/zqingru/DataLog/sft_ultrafeedback-gpt4-response_mistral-7b/mistral-7b-tulu-sft-ep2/us-west-2/sft_lr-1e-06_bs-128_len-2048_sample-9366_epoch-10_seed9/save_checkpoint"
    model_kwargs:
      dtype: 'bfloat16'
      tokenizer_mode: 'auto'
    max_new_tokens: 2048
    # do_sample: true
    seed: 9
    temperature: 0.9
    top_p: 1.0
    batch_size: 900
  pretty_name: "mistral-7b_sft"