Llama-3-8B_chat-prompt_hf-generate:
  prompt_template: "llama-2-7b-chat-hf/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "meta-llama/Meta-Llama-3-8B"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    do_sample: true
    # seed: 42
    temperature: 0.9
    top_p: 1.0
    batch_size: 6
  pretty_name: "Llama-3-8B_chat-prompt_hf-generate"