llama3-8b_ppo-seqrm_critic-pretrain-59_lr-1e-07-9e-06_warmup-10_kl-0.02_epoch-1-1_step59_vllm:
  prompt_template: "llama3-8b_ultrafeedback_ppo/prompt_template.txt"
  fn_completions: "vllm_local_completions"
  completions_kwargs:
    model_name: "/fsx-Training/home/zqingru/DataLog/ppo-fsfairx-seqrm_ultrafeedback_llama3-8b-sft/us-west-2/ppo-reward-seqrm_lr-1e-07-9e-06_warmup-10_kl-0.02_bs-128-1024_sample-60908_epoch-1-1_seed9_critic-pretrain-59/save_model"
    model_kwargs:
      dtype: 'bfloat16'
      tokenizer_mode: 'auto'
    max_new_tokens: 2048
    # do_sample: true
    seed: 9
    temperature: 0.9
    top_p: 1.0
    batch_size: 900
  pretty_name: "llama3-8b_ppo-seqrm_critic-pretrain-59_lr-1e-07-9e-06_warmup-10_kl-0.02_epoch-1-1_step59_vllm"