Llama-3-8B-Tulu-PPO_lr-5e-07-9e-06_warmup-10_step40_hf:
  prompt_template: "Llama-3-8B-Tulu-SFT/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "/fsx-Training/home/zqingru/DataLog/tulu-ultrafeedback_ppo-fsfairx-rm_llama3-8b-sft/ppo_lr-5e-07-9e-06_warmup-10_bs-128-1024_sample-60908_epoch-2-1_seed9/training_checkpoints/save_checkpoint/global_step40"
    model_kwargs:
      torch_dtype: 'float16'
    max_new_tokens: 2048
    do_sample: true
    # seed: 42
    temperature: 0.9
    top_p: 1.0
    batch_size: 6
  pretty_name: "Llama-3-8B-Tulu-PPO_lr-5e-07-9e-06_warmup-10_step40_hf"